name: develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install node and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build --if-present
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: last-built-artifact
          path: |
            dist
          retention-days: 7
  
  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: last-built-artifact

      - name: Build Docker Image
        run: docker build -t ghcr.io/lotostudio/financial-web:develop .
      
      - name: Login
        run: echo $TOKEN | docker login ghcr.io -u $USER --password-stdin
        env:
          USER: ${{ secrets.USER }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: Push Docker Image
        run: docker push ghcr.io/lotostudio/financial-web:develop
